p8105_hw1_iho2104
================
Ixtaccihuatl Obregon
2023-09-20

``` r
library(moderndive)
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(ggplot2)
```

# The data

``` r
data("early_january_weather")
view(early_january_weather)
```

# Row, Columns, and Mean of the Data

``` r
nrow(early_january_weather)
```

    ## [1] 358

``` r
ncol(early_january_weather)
```

    ## [1] 15

``` r
early_january_weather %>% 
  pull(temp) %>% 
  mean()
```

    ## [1] 39.58212

The variables in this dataset are origin, year, month, day, hour, temp,
dew point, humidity, wind, and wind speed, etc.

The size of the dataset is 358 x 15.

The mean temperature was about 39.58

# Scatterplot of time vs temp

``` r
ggplot(early_january_weather, 
       aes(x = time_hour, y = temp)) + geom_point(aes(colour=humid))
```

![](p8105_hw1_iho2104_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

The scatterplot shows the hourly change in temperature, meaning the
day-night temp cycle is shown. Temperature rises from Jan 07 to Jan 14,
with higher temperature having a higher humidity point.

# Save plot with ggsave

``` r
ggsave("early_january_weather.pdf")
```

    ## Saving 7 x 5 in image
